name: Update Requirements
on:
  schedule:
    # runs daily at 04:05 am
    - cron: '5 4 * * *'
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the head commit of the branch
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0
    - run: |
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        make update -m "[RELEASE] %s"

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Push changes
      uses: ad-m/github-push-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
    - uses: fastify/github-action-merge-dependabot@v2.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
