name: Auto update Python dependencies
on:
  schedule:
    # runs daily at 04:05 am
    - cron: '5 4 * * *'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git checkout -b rc_update
          make update
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated requirements"
          git push rc_update