name: Auto update rust dependencies
on:
  schedule:
    # runs daily at 04:05 am
    - cron: '5 11 * * *'
  workflow_dispatch:

jobs:
  update_requirements:
    uses: emZubair/selenium-boilerplate.git/.github/workflows/compile-python-requirements.yaml@staging
